name: Python Testing

on:
  push:
    branches:
      - main

jobs:
  running-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repo
        uses: actions/checkout@v3
      - name: Python env setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Running the python script
        run: python main.py
        
